create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    name text not null,
    education text not null,
    preferred_location text not null default 'India',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.skills (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamptz not null default now()
);

create table public.profile_skills (
    profile_id uuid not null references public.profiles(id) on delete cascade,
    skill_id bigint not null references public.skills(id) on delete cascade,
    created_at timestamptz not null default now(),

    primary key (profile_id, skill_id)
);

create table public.learning_resources (
    id bigint generated by default as identity primary key,
    skill text not null,
    title text not null,
    resource_type text not null,
    url text not null,
    description text not null,
    created_at timestamptz not null default now()
);