create table public.internships (
    id bigint generated by default as identity primary key,
    title text not null,
    company text not null,
    location text,
    description text,
    source text,
    url text,
    created_at timestamptz not null default now()
);

create table public.internship_requirements (
    id bigint generated by default as identity primary key,
    internship_id bigint not null references public.internships(id) on delete cascade,
    skill text not null,
    requirement_type text not null,
    created_at timestamptz not null default now(),

    constraint internship_requirements_type_check
        check (requirement_type in ('required', 'preferred'))
);