create table public.aptitude_questions (
    id bigint generated by default as identity primary key,
    category text not null,
    difficulty text not null,
    question text not null,
    options jsonb not null,
    correct_answer text not null,
    created_at timestamptz not null default now()
);

create table public.aptitude_attempts (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    category text not null,
    difficulty text not null,
    total_questions integer not null,
    correct_answers integer not null,
    incorrect_answers integer not null,
    score integer not null,
    accuracy numeric(5,2) not null,
    weak_area text,
    created_at timestamptz not null default now()
);

create table public.aptitude_answers (
    id bigint generated by default as identity primary key,
    attempt_id bigint not null references public.aptitude_attempts(id) on delete cascade,
    question_id bigint not null references public.aptitude_questions(id) on delete cascade,
    selected_answer text not null,
    is_correct boolean not null,
    created_at timestamptz not null default now()
);

