create table public.applications (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    application_id text not null,
    internship_id text not null,
    title text not null,
    company text not null,
    application_url text not null,
    status text not null default 'Applied',
    created_at timestamptz not null default now(),

    constraint applications_status_check
        check (status in ('Applied', 'Shortlisted', 'Interview', 'Rejected', 'Selected')),

    constraint applications_user_application_unique
        unique (user_id, application_id)
);

create table public.watchlist (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    internship_id text not null,
    title text not null,
    company text not null,
    location text not null,
    application_url text not null,
    deadline date,
    created_at timestamptz not null default now(),

    constraint watchlist_user_internship_unique
        unique (user_id, internship_id)
);